# -*- mode: ruby -*-
# vi: set ft=ruby :
	
Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
	
    centos.vm.provider "virtualbox" do |v|
	  v.name = "CentOS 7"
	  v.memory = 2048
      v.cpus = 2
    end
	
	centos.vm.network "private_network", ip: "192.168.0.2",
      virtualbox__intnet: "mynetwork"
  end
  
  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
	
    kali.vm.provider "virtualbox" do |v|
	  v.name = "Kali Linux"
	  v.memory = 2048
      v.cpus = 2
    end
	
	kali.vm.network "private_network", ip: "192.168.0.1",
      virtualbox__intnet: "mynetwork"
  end
  
end
